---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:M-Wittner/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: eu.gcr.io/boreal-byte-270613/echo
      tag: dev-dzdvdzmq
    replicaCount: 1
    # mongodb:
    #   port: "3000"
    #   loglevel: info
    #   persist: "true"
    #   dbname: "echo"
    #   mongodburl: bW9uZ29kYjovL3VzZXI6MTIzNEBtb25nby0wLm1vbmdvLG1vbmdvLTEubW9uZ28sbW9uZ28tMi5tb25nbzoyNzAxNy9lY2hvP2F1dGhTb3VyY2U9YWRtaW4K
