replicaCount: 1

image:
  repository: eu.gcr.io/boreal-byte-270613/echo
  tag: "2.0"
  pullPolicy: IfNotPresent
  
service:
  type: ClusterIP
  port: 80
  name: http

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "echo-prod-issuer"
  hosts:
    - host: www.wittner.tk
      paths:
        - backend:
            serviceName: echo-service
            servicePort: 80
  tls:
    - secretName: echo-prod-tls
      hosts:
        - www.wittner.tk
env:
  configMap: echo-config-map-env
  secret: mongo-url

resources: 
  requests: 
    memory: "16Mi" 
    cpu: "1m" 
  limits: 
    memory: "128Mi" 
    cpu: "100m"

mongodb:
  port: "3000"
  loglevel: info
  persist: "true"
  dbname: "echo"
  mongodburl: bW9uZ29kYjovL3VzZXI6MTIzNEBtb25nby0wLm1vbmdvLG1vbmdvLTEubW9uZ28sbW9uZ28tMi5tb25nbzoyNzAxNy9lY2hvP2F1dGhTb3VyY2U9YWRtaW4K
  # mongodburl: bW9uZ29kYjovL2VjaG91c2VyOnBhc3N3b3JkMTIzQG1vbmdvZGIuZGI6MjcwMTcvZWNoby1zdGFnaW5nCg==
