apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: echo-config-map-env
            - secretRef:
                name: mongo-url
          resources:
            requests:
              memory: "{{ .Values.resources.reqMem }}"
              cpu: "{{ .Values.resources.reqCpu }}"
            limits:
              memory: "{{ .Values.resources.limitMem }}"
              cpu: "{{ .Values.resources.limitCpu }}"
            
            