{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    nginx.org/proxy-connect-timeout: "900s"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: echo-prod
spec:
  rules:
  {{ range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
  {{ end }}
  - http:
      paths:
      - backend:
          serviceName: echo-service
          servicePort: 80
{{ end }}
