apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      name: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Chart.Name }}
